### PR TITLE
Fixed min error message

### PR DESCRIPTION
**Pull request by MarcusNoble**
Changed error message for `min`. 

**Before:**
`"message": "customer.firstName over max with value 0 (min is 1)"`
**After:** 
`"message": "customer.firstName under min with value 0 (min is 1)"`

### CODE REVIEW

**Comment by brianleroux** [comment]
tx!

**Comment by brianleroux** [comment]
thx!!

**Comment by brianleroux** [comment]
fyi just published this fix to npm / thx again 💯

**Comment by MarcusNoble** [comment]
Brilliant! Thanks!

**Pull request merged**
